server:
    port: 8080

spring:
#    autoconfigure:
#        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    jpa:
        hibernate:
            ddl-auto: none
            default_schema: DEFAULT
        database: postgresql
    h2:
        console:
            enabled: 'true'
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/jasonbourn
        username: postgres
        password': 1234